#:schema https://fnox.jdx.dev/schema.json

if_missing = "error"

[providers]
keychain = { type = "keychain", service = "zapper-xyz-api" }
pass = { type = "password-store", prefix = "zapper-xyz-api/" }
